name: Podspec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test Podspec 
      run: pod lib lint --verbose --no-clean --allow-warnings TossPayments.podspec
