name: Deploy to cocoapods

on:
  push:
    paths:
      - 'version'
jobs:
  Deploy:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: sh ./script/release.sh