name: Deploy to cocoapods

on:
  push:
    branches: [ "main" ]
jobs:
  Deploy:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push TossPayments.podspec --allow-warnings
